### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by dltmdrbtjd** [mael1657/PBL_week1#1]
- 프로젝트 마무리 하시느라 고생 많으셨습니다 😎 

- redux-toolkit을 사용하셨군요 ! 혹시 컴포넌트에서 서버에 직접 요청하고 다시 store에 담는 구조로 개발하신 이유가 있을까요 ? redux-toolkit의 middleware함수 기능을 사용하셔서 같은 store파일에서 middleware를 만들어서 사용하시고 컴포넌트에서 dispatch만 시켜주는 식으로 개발하셨다면 좀 더 좋은 방식이 되었을것 같습니다. 만약 이런 구조라면 사실 redux를 사용하지 않아도 무방합니다 ! 혹시 redux-toolkit의 미들웨어 함수 기능을 모르고 계시다면 https://redux-toolkit.js.org/api/createAsyncThunk 해당 문서를 참고해보시고 리팩토링을 진행해보셔도 좋은 경험이 될 것 같아요 😄

**Comment by O-h-y-o** [comment]
안녕하세요 주현님! 한 주 동안 고생 많으셨습니다.

- 리덕스와 파이어스토어의 연결 구조가 이게 맞나 싶네요

> 리액트에 파이어베이스를 연결시키는 것을 말씀하신걸까요? 리덕스와 파이어스토어는 별개입니다..!! 연동은 잘 하셨습니다!
